# Generated by Django 5.2.5 on 2025-08-19 21:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
