# Generated by Django 5.2.5 on 2025-08-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ultimas_noticias',
            field=models.BooleanField(default=False),
        ),
    ]
