# Generated by Django 5.2.5 on 2025-08-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_banner_post_ultimas_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_video', models.CharField(max_length=200)),
                ('id_video', models.CharField(max_length=20)),
            ],
        ),
    ]
