# Generated by Django 5.2.5 on 2025-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_youtubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
