# Generated by Django 5.2.5 on 2025-08-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_youtubevideo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breakingnews',
            options={'ordering': ['-data_publicacao']},
        ),
        migrations.AddField(
            model_name='breakingnews',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
