# Generated by Django 5.2.5 on 2025-08-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_patrocinadore'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='autores/'),
        ),
    ]
