# Generated by Django 5.2.5 on 2025-08-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_subcategoria_slug_alter_autor_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_imagem', models.ImageField(upload_to='instagram/posts/')),
                ('curtidas', models.PositiveIntegerField(default=0)),
                ('legenda', models.TextField(blank=True)),
                ('hashtags', models.CharField(blank=True, max_length=200)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('link_externo', models.URLField(blank=True, default='https://www.instagram.com/canalareiabranca/')),
            ],
            options={
                'verbose_name': 'Post do Instagram',
                'verbose_name_plural': 'Posts do Instagram',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
