# Generated by Django 5.2.5 on 2025-08-28 00:09

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
